<a href="https://colab.research.google.com/github/AniruddhaChaudhury2006/CreditCardFraudDetection/blob/main/Credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head() #displaying 1st 5 rows

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail() #displaying last 5 rows

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
225830,144415.0,2.042317,-0.143495,-2.954711,-0.579241,2.610433,3.142249,-0.418329,0.784676,0.360031,...,-0.352994,-0.996361,0.364446,0.604771,-0.264159,0.219787,-0.039003,-0.042977,0.89,0.0
225831,144416.0,1.966844,-0.845034,-0.107284,-1.487196,-1.204514,-0.599232,-0.949943,0.058269,2.101038,...,0.142264,0.676792,0.243586,0.060568,-0.401395,-0.333401,0.057084,-0.040454,9.99,0.0
225832,144416.0,0.081639,0.619585,-1.592527,-1.516643,3.044799,3.289021,0.443155,0.814793,-0.161410,...,0.370831,1.207109,-0.075940,0.738220,-0.753429,-0.199296,0.526399,0.316053,9.99,0.0
225833,144416.0,-0.434838,1.277109,-3.562713,-1.377520,3.088281,2.657429,0.205473,1.432107,-0.856572,...,0.249104,0.461120,0.007146,0.663661,-0.333725,0.556364,-0.308303,-0.063254,8.80,0.0
225834,144416.0,-5.201061,-1.797970,-0.343040,1.980920,0.287586,-0.429028,-0.110910,0.195588,1.216880,...,-1.247245,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
credit_card_data.info() #dataset information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225835 entries, 0 to 225834
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    225835 non-null  float64
 1   V1      225835 non-null  float64
 2   V2      225835 non-null  float64
 3   V3      225835 non-null  float64
 4   V4      225835 non-null  float64
 5   V5      225835 non-null  float64
 6   V6      225835 non-null  float64
 7   V7      225835 non-null  float64
 8   V8      225835 non-null  float64
 9   V9      225835 non-null  float64
 10  V10     225835 non-null  float64
 11  V11     225835 non-null  float64
 12  V12     225835 non-null  float64
 13  V13     225835 non-null  float64
 14  V14     225835 non-null  float64
 15  V15     225835 non-null  float64
 16  V16     225835 non-null  float64
 17  V17     225835 non-null  float64
 18  V18     225835 non-null  float64
 19  V19     225835 non-null  float64
 20  V20     225835 non-null  float64
 21  V21     225835 non-null  float64
 22  V22     225835 non-null  float64
 23  V23     225834 non-null  float64
 24  V24     225834 non-null  float64
 25  V25     225834 non-null  float64
 26  V26     225834 non-null  float64
 27  V27     225834 non-null  float64
 28  V28     225834 non-null  float64
 29  Amount  225834 non-null  float64
 30  Class   225834 non-null  float64
dtypes: float64(31)
memory usage: 53.4 MB

In [ ]:
credit_card_data.isnull().sum() #checking for null values

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
credit_card_data['Class'].value_counts() #distribution of legit transactions & fraudulent transactions

Class
0.0    225419
1.0       415
Name: count, dtype: int64

**HIGHLY UNBALANCED DATASET WHERE 0 DENOTES NORMAL TRANSACTION AND 1 DENOTES FRAUD ONE**

In [ ]:
# separating data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(legit.shape)
print(fraud.shape)

(225419, 31)
(415, 31)

In [ ]:
legit.Amount.describe() #statistical measures of data

count    225419.000000
mean         90.744375
std         250.141954
min           0.000000
25%           6.000000
50%          23.400000
75%          79.955000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     415.000000
mean      124.653398
std       256.043305
min         0.000000
25%         1.000000
50%        12.310000
75%       106.725000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()   #comparing values for both transactions

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,78478.303932,-0.060435,-0.020045,0.204692,0.037688,-0.059293,0.034347,-0.016559,0.003799,0.007351,...,0.009627,-0.008041,-0.024008,-0.010307,0.001281,0.039669,0.003145,-0.000076,0.00194,90.744375
1.0,66934.766265,-5.385937,3.966763,-7.457503,4.664025,-3.779142,-1.356134,-6.279493,0.656473,-2.698293,...,0.381241,0.766231,0.012771,-0.054751,-0.082825,0.047755,0.038529,0.199928,0.06061,124.653398

In [ ]:
legit_sample = legit.sample(n=415) # building sample dataset containing similar distribution of normal and fraudulent transactions (under sampling)

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
126457,78010.0,1.218101,0.694528,-0.453588,1.154531,0.337580,-0.722196,0.228792,-0.099684,-0.387625,...,-0.033092,-0.037810,-0.181314,-0.119402,0.718112,-0.325815,0.033568,0.044839,1.00,0.0
102818,68378.0,1.146060,0.130488,0.283920,1.201850,0.047080,0.326039,-0.061425,0.168895,0.095585,...,-0.075283,-0.026684,-0.111118,-0.295024,0.667853,-0.308905,0.033948,0.001825,7.74,0.0
78903,57763.0,-4.540111,-1.097048,0.595332,1.308387,0.983138,-1.840283,-1.367998,0.524208,0.125721,...,-0.621696,-0.835758,-2.071037,0.615601,-0.340132,0.282638,1.116015,-1.186601,16.99,0.0
100043,67395.0,-1.318688,1.179285,0.770779,0.262400,-0.788199,-0.216959,-0.402388,1.088412,0.195729,...,0.082250,0.209720,-0.008054,0.082908,-0.239929,0.391668,-0.015412,0.047442,1.00,0.0
116947,74487.0,1.160862,-0.110026,0.911639,1.163437,-0.563853,0.299246,-0.516596,0.116082,0.887556,...,-0.097051,-0.110362,-0.136043,-0.433113,0.530289,-0.361319,0.068868,0.035288,35.97,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
222419,142961.0,0.457845,1.373769,-0.488926,2.805351,1.777386,0.100492,1.295016,-0.135857,-1.695822,...,0.105593,0.371014,0.051105,0.401524,-0.724766,-0.202881,0.092124,0.094956,0.0,1.0
223366,143354.0,1.118331,2.074439,-3.837518,5.448060,0.071816,-1.020509,-1.808574,0.521744,-2.032638,...,0.289861,-0.172718,-0.021910,-0.376560,0.192817,0.114107,0.500996,0.259533,1.0,1.0
223572,143434.0,-2.729482,3.312495,-4.242710,5.036985,-0.376561,-1.532462,-3.449159,1.856839,-3.623334,...,0.727415,-0.301432,-0.502433,-0.462309,0.510683,0.046665,0.514646,0.140999,1.0,1.0
223578,143438.0,-5.256434,0.364541,-5.412085,2.400031,0.697301,-1.998755,-5.835532,-0.887739,-2.828287,...,-0.648259,0.511285,-1.110045,0.178987,0.220235,-0.699809,0.580487,-0.173630,8.9,1.0
223618,143456.0,-2.006582,3.676577,-5.463811,7.232058,-1.627859,-0.996755,-4.299833,2.268867,-3.651067,...,0.713907,-0.063868,0.167947,-0.449864,0.023702,0.536905,0.485864,-0.042393,1.0,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    415
1.0    415
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,77055.918072,-0.105989,-0.042905,0.153786,0.114681,-0.043504,0.016432,0.031807,-0.017180,0.026110,...,0.021228,-0.057580,0.026124,0.016475,-0.033843,0.079355,-0.002464,0.039058,0.01277,94.786434
1.0,66934.766265,-5.385937,3.966763,-7.457503,4.664025,-3.779142,-1.356134,-6.279493,0.656473,-2.698293,...,0.381241,0.766231,0.012771,-0.054751,-0.082825,0.047755,0.038529,0.199928,0.06061,124.653398

In [ ]:
X = new_dataset.drop(columns='Class', axis = 1) #SPLITTING DATASET INTO FEATURES AND TARGETS
Y = new_dataset['Class']
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
126457   78010.0  1.218101  0.694528 -0.453588  1.154531  0.337580 -0.722196
102818   68378.0  1.146060  0.130488  0.283920  1.201850  0.047080  0.326039
78903    57763.0 -4.540111 -1.097048  0.595332  1.308387  0.983138 -1.840283
100043   67395.0 -1.318688  1.179285  0.770779  0.262400 -0.788199 -0.216959
116947   74487.0  1.160862 -0.110026  0.911639  1.163437 -0.563853  0.299246
...          ...       ...       ...       ...       ...       ...       ...
222419  142961.0  0.457845  1.373769 -0.488926  2.805351  1.777386  0.100492
223366  143354.0  1.118331  2.074439 -3.837518  5.448060  0.071816 -1.020509
223572  143434.0 -2.729482  3.312495 -4.242710  5.036985 -0.376561 -1.532462
223578  143438.0 -5.256434  0.364541 -5.412085  2.400031  0.697301 -1.998755
223618  143456.0 -2.006582  3.676577 -5.463811  7.232058 -1.627859 -0.996755

              V7        V8        V9  ...       V20       V21       V22  \
126457  0.228792 -0.099684 -0.387625  ... -0.051133 -0.033092 -0.037810
102818 -0.061425  0.168895  0.095585  ... -0.187531 -0.075283 -0.026684
78903  -1.367998  0.524208  0.125721  ... -0.663553 -0.621696 -0.835758
100043 -0.402388  1.088412  0.195729  ... -0.339951  0.082250  0.209720
116947 -0.516596  0.116082  0.887556  ... -0.027905 -0.097051 -0.110362
...          ...       ...       ...  ...       ...       ...       ...
222419  1.295016 -0.135857 -1.695822  ... -0.264705  0.105593  0.371014
223366 -1.808574  0.521744 -2.032638  ...  0.163513  0.289861 -0.172718
223572 -3.449159  1.856839 -3.623334  ...  0.164288  0.727415 -0.301432
223578 -5.835532 -0.887739 -2.828287  ... -0.403685 -0.648259  0.511285
223618 -4.299833  2.268867 -3.651067  ...  0.474414  0.713907 -0.063868

             V23       V24       V25       V26       V27       V28  Amount
126457 -0.181314 -0.119402  0.718112 -0.325815  0.033568  0.044839    1.00
102818 -0.111118 -0.295024  0.667853 -0.308905  0.033948  0.001825    7.74
78903  -2.071037  0.615601 -0.340132  0.282638  1.116015 -1.186601   16.99
100043 -0.008054  0.082908 -0.239929  0.391668 -0.015412  0.047442    1.00
116947 -0.136043 -0.433113  0.530289 -0.361319  0.068868  0.035288   35.97
...          ...       ...       ...       ...       ...       ...     ...
222419  0.051105  0.401524 -0.724766 -0.202881  0.092124  0.094956    0.00
223366 -0.021910 -0.376560  0.192817  0.114107  0.500996  0.259533    1.00
223572 -0.502433 -0.462309  0.510683  0.046665  0.514646  0.140999    1.00
223578 -1.110045  0.178987  0.220235 -0.699809  0.580487 -0.173630    8.90
223618  0.167947 -0.449864  0.023702  0.536905  0.485864 -0.042393    1.00

[830 rows x 30 columns]

In [ ]:
print(Y)

126457    0.0
102818    0.0
78903     0.0
100043    0.0
116947    0.0
         ...
222419    1.0
223366    1.0
223572    1.0
223578    1.0
223618    1.0
Name: Class, Length: 830, dtype: float64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2) #splitting dataset into training and testing data

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(830, 30) (664, 30) (166, 30)

In [ ]:
model = LogisticRegression() #model training using logistic regression
model.fit(X_train, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train_prediction = model.predict(X_train) #evaluating model using accuracy score
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print("Accuracy on training data : ", training_data_accuracy)

Accuracy on training data :  0.9457831325301205

In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print("Accuracy on test data : ", test_data_accuracy)

Accuracy on test data :  0.9216867469879518

In [ ]:
input_data = (13, -0.436905071360625,0.918966212909322,0.92459077438817,-0.727219053596792,0.915678718106307,-0.127867352079254,0.707641607333935,0.0879623554672504,-0.66527135413364,-0.737979823596458,0.32409781346169,0.277192107214981,0.252624256310781,-0.291896460370468,-0.184520169327133,1.14317370716197,-0.92870926272403,0.680469592634687,0.0254364616880793,-0.0470212823165035,-0.194795823794671,-0.672637997017793,-0.156857514491897,-0.888386320943716,-0.342413218776576,-0.049026728633951,0.0796923991551505,0.131023789452311,0.89) #building predictive system
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)
if(prediction[0] == 0):
  print("Normal transaction")
else:
  print("Fraud transaction")

[0.]
Normal transaction

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(